## Day 3: Lobby
### Part 1
**_You descend a short staircase, enter the surprisingly vast lobby, and are quickly cleared by the security checkpoint. When you get to the main elevators, however, you discover that each one has a red light above it_**: they're all offline.

"Sorry about that," an Elf apologizes as she tinkers with a nearby control panel. "Some kind of electrical surge seems to have fried them. I'll try to get them online soon."

You explain your need to get further underground. "Well, you could at least take the escalator down to the printing department, not that you'd get much further than that without the elevators working. That is, you could if the escalator weren't also offline."

"But, don't worry! It's not fried; it just needs power. Maybe you can get it running while I keep working on the elevators."

**_There are batteries nearby that can supply emergency power to the escalator for just such an occasion. The batteries are each labeled with their joltage rating, a value from 1 to 9. You make a note of their joltage ratings (your puzzle input). For example_**:

- 987654321111111
- 811111111111119
- 234234234234278
- 818181911112111

The batteries are arranged into banks; each line of digits in your input corresponds to a single bank of batteries. Within each bank, you need to turn on exactly two batteries; the joltage that the bank produces is equal to the number formed by the digits on the batteries you've turned on. For example, if you have a bank like 12345 and you turn on batteries 2 and 4, the bank would produce 24 jolts. (You cannot rearrange batteries.)

**_You'll need to find the largest possible joltage each bank can produce. In the above example_**:

In 987654321111111, you can make the largest joltage possible, 98, by turning on the first two batteries.
In 811111111111119, you can make the largest joltage possible by turning on the batteries labeled 8 and 9, producing 89 jolts.
In 234234234234278, you can make 78 by turning on the last two batteries (marked 7 and 8).
In 818181911112111, the largest joltage you can produce is 92.
The total output joltage is the sum of the maximum joltage from each bank, so in this example, the total output joltage is 98 + 89 + 78 + 92 = 357.

There are many batteries in front of you. Find the maximum joltage possible from each bank; what is the total output joltage?

In [32]:
with open('test_input.txt') as f:
    test_banks = []
    for line in f: 
        test_banks.append(line.strip())

test_banks

['987654321111111', '811111111111119', '234234234234278', '818181911112111']

In [33]:
def get_max_joltage(banks): 
    def find_max_battery(remaining_bank, ind=-1): 
        max_battery = 0
        max_index = 0
        for i, battery in enumerate(remaining_bank):
            if i == len(remaining_bank) + ind: 
                break 
            if int(battery) > max_battery: 
                max_battery = int(battery)
                max_index = i
        return max_battery, max_index
    
    all_joltages = []

    for bank in banks: 
        max_battery_first, max_index = find_max_battery(bank)
        remaining_bank = bank[max_index+1:]
        max_battery_second, _ = find_max_battery(remaining_bank, 0)

        all_joltages.append(10*max_battery_first + max_battery_second)

    return sum(all_joltages)
    

In [34]:
get_max_joltage(test_banks)

357

In [35]:
with open('input.txt') as f:
    banks = []
    for line in f: 
        banks.append(line.strip())

get_max_joltage(banks)

17278

### Part 2
The escalator doesn't move. The Elf explains that it probably needs more joltage to overcome the static friction of the system and hits the big red "joltage limit safety override" button. You lose count of the number of times she needs to confirm "yes, I'm sure" and decorate the lobby a bit while you wait.

Now, you need to make the largest joltage by turning on exactly twelve batteries within each bank.

The joltage output for the bank is still the number formed by the digits of the batteries you've turned on; the only difference is that now there will be 12 digits in each bank's joltage output instead of two.

**_Consider again the example from before_**:

- 987654321111111
- 811111111111119
- 234234234234278
- 818181911112111

**_Now, the joltages are much larger_**:

In 987654321111111, the largest joltage can be found by turning on everything except some 1s at the end to produce 987654321111.
In the digit sequence 811111111111119, the largest joltage can be found by turning on everything except some 1s, producing 811111111119.
In 234234234234278, the largest joltage can be found by turning on everything except a 2 battery, a 3 battery, and another 2 battery near the start to produce 434234234278.
In 818181911112111, the joltage 888911112111 is produced by turning on everything except some 1s near the front.
**_The total output joltage is now much larger_**: 987654321111 + 811111111119 + 434234234278 + 888911112111 = 3121910778619.

What is the new total output joltage?

In [36]:
def get_max_joltage_new(banks, batteries = 12): 
    def find_max_battery(remaining_bank, ind): 
        max_battery = 0
        max_index = 0
        for i, battery in enumerate(remaining_bank):
            if i == len(remaining_bank) + ind: 
                break 
            if int(battery) > max_battery: 
                max_battery = int(battery)
                max_index = i
        return max_battery, max_index
    
    all_joltages = []
    for bank in banks: 
        all_batteries = ''
        remaining_bank = bank
        for i in range(batteries): 
            ind = i - 12 + 1
            # print('ind', ind)
            max_battery, max_index = find_max_battery(remaining_bank, ind)
            # print('remaining bank', remaining_bank)
            remaining_bank = remaining_bank[max_index+1:]
            all_batteries += str(max_battery)
            # print('batteries', all_batteries)
        all_joltages.append(int(all_batteries))
        # print(all_joltages)
        
    return sum(all_joltages)

In [37]:
get_max_joltage_new(test_banks) # Expected: 3121910778619

3121910778619

In [38]:
get_max_joltage_new(banks)

171528556468625